CREATE DATABASE TESTE_UNICAD
GO

USE TESTE_UNICAD
GO

CREATE TABLE ENTREGAS
(
ENTREGA INT IDENTITY PRIMARY KEY,
NOME_CLIENTE VARCHAR(50),
DATA_ENTREGA DATETIME,
PONTO_PARTIDA VARCHAR(100),
PONTO_DESTINO VARCHAR(100),
)
GO